# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1174, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1184, 581))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, -1, 200, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.song_name_text = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.song_name_text.setObjectName("song_name_text")
        self.verticalLayout_5.addWidget(self.song_name_text)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.play_pause_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.play_pause_button.setEnabled(False)
        self.play_pause_button.setObjectName("play_pause_button")
        self.horizontalLayout_4.addWidget(self.play_pause_button)
        self.stop_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.stop_button.setEnabled(False)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_4.addWidget(self.stop_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 40, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.effect_1_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.effect_1_checkbox.setEnabled(False)
        self.effect_1_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.effect_1_checkbox.setObjectName("effect_1_checkbox")
        self.verticalLayout_4.addWidget(self.effect_1_checkbox)
        self.effect_2_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.effect_2_checkbox.setEnabled(False)
        self.effect_2_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.effect_2_checkbox.setObjectName("effect_2_checkbox")
        self.verticalLayout_4.addWidget(self.effect_2_checkbox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.freq_labels_layout = QtWidgets.QHBoxLayout()
        self.freq_labels_layout.setContentsMargins(40, -1, 40, -1)
        self.freq_labels_layout.setObjectName("freq_labels_layout")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.freq_labels_layout.addWidget(self.label_10)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.freq_labels_layout.addWidget(self.label_7)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.freq_labels_layout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.freq_labels_layout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.freq_labels_layout.addWidget(self.label_8)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.freq_labels_layout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.freq_labels_layout.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.freq_labels_layout.addWidget(self.label_9)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.freq_labels_layout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.freq_labels_layout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.freq_labels_layout)
        self.slider_layout = QtWidgets.QHBoxLayout()
        self.slider_layout.setObjectName("slider_layout")
        self.verticalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider.setMinimum(-100)
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setProperty("value", 0)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.slider_layout.addWidget(self.verticalSlider)
        self.verticalSlider_4 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_4.setMinimum(-100)
        self.verticalSlider_4.setMaximum(100)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.slider_layout.addWidget(self.verticalSlider_4)
        self.verticalSlider_3 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_3.setMinimum(-100)
        self.verticalSlider_3.setMaximum(100)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.slider_layout.addWidget(self.verticalSlider_3)
        self.verticalSlider_2 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_2.setMinimum(-100)
        self.verticalSlider_2.setMaximum(100)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.slider_layout.addWidget(self.verticalSlider_2)
        self.verticalSlider_5 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_5.setMinimum(-100)
        self.verticalSlider_5.setMaximum(100)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.slider_layout.addWidget(self.verticalSlider_5)
        self.verticalSlider_7 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_7.setMinimum(-100)
        self.verticalSlider_7.setMaximum(100)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        self.slider_layout.addWidget(self.verticalSlider_7)
        self.verticalSlider_10 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_10.setMinimum(-100)
        self.verticalSlider_10.setMaximum(100)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName("verticalSlider_10")
        self.slider_layout.addWidget(self.verticalSlider_10)
        self.verticalSlider_6 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_6.setMinimum(-100)
        self.verticalSlider_6.setMaximum(100)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.slider_layout.addWidget(self.verticalSlider_6)
        self.verticalSlider_9 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_9.setMinimum(-100)
        self.verticalSlider_9.setMaximum(100)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName("verticalSlider_9")
        self.slider_layout.addWidget(self.verticalSlider_9)
        self.verticalSlider_8 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.verticalSlider_8.setMinimum(-100)
        self.verticalSlider_8.setMaximum(100)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName("verticalSlider_8")
        self.slider_layout.addWidget(self.verticalSlider_8)
        self.verticalLayout_2.addLayout(self.slider_layout)
        self.freq_values_layout = QtWidgets.QHBoxLayout()
        self.freq_values_layout.setContentsMargins(40, -1, 40, -1)
        self.freq_values_layout.setObjectName("freq_values_layout")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.freq_values_layout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.freq_values_layout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.freq_values_layout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.freq_values_layout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.freq_values_layout.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.freq_values_layout.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.freq_values_layout.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.freq_values_layout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.freq_values_layout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.freq_values_layout.addWidget(self.label_20)
        self.verticalLayout_2.addLayout(self.freq_values_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 5)
        self.verticalLayout_2.setStretch(4, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1174, 22))
        self.menubar.setObjectName("menubar")
        self.menuEqualizer = QtWidgets.QMenu(self.menubar)
        self.menuEqualizer.setObjectName("menuEqualizer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Music_File = QtWidgets.QAction(MainWindow)
        self.actionNew_Music_File.setObjectName("actionNew_Music_File")
        self.menuEqualizer.addAction(self.actionNew_Music_File)
        self.menubar.addAction(self.menuEqualizer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.song_name_text.setText(_translate("MainWindow", "Выберите песню"))
        self.play_pause_button.setText(_translate("MainWindow", "Воспроизвести"))
        self.stop_button.setText(_translate("MainWindow", "Остановить"))
        self.effect_1_checkbox.setText(_translate("MainWindow", "Реверберация"))
        self.effect_2_checkbox.setText(_translate("MainWindow", "Овердрайв"))
        self.label_10.setText(_translate("MainWindow", "0-1 Gh"))
        self.label_7.setText(_translate("MainWindow", "1-2Gh"))
        self.label_4.setText(_translate("MainWindow", "1-2Gh"))
        self.label_6.setText(_translate("MainWindow", "1-2Gh"))
        self.label_8.setText(_translate("MainWindow", "1-2Gh"))
        self.label_3.setText(_translate("MainWindow", "1-2Gh"))
        self.label_5.setText(_translate("MainWindow", "1-2Gh"))
        self.label_9.setText(_translate("MainWindow", "1-2Gh"))
        self.label_2.setText(_translate("MainWindow", "1-2Gh"))
        self.label.setText(_translate("MainWindow", "1-2Gh"))
        self.label_11.setText(_translate("MainWindow", "0 dB"))
        self.label_12.setText(_translate("MainWindow", "0 dB"))
        self.label_13.setText(_translate("MainWindow", "0 dB"))
        self.label_14.setText(_translate("MainWindow", "0 dB"))
        self.label_15.setText(_translate("MainWindow", "0 dB"))
        self.label_16.setText(_translate("MainWindow", "0 dB"))
        self.label_17.setText(_translate("MainWindow", "0 dB"))
        self.label_18.setText(_translate("MainWindow", "0 dB"))
        self.label_19.setText(_translate("MainWindow", "0 dB"))
        self.label_20.setText(_translate("MainWindow", "0 dB"))
        self.menuEqualizer.setTitle(_translate("MainWindow", "Equalizer"))
        self.actionNew_Music_File.setText(_translate("MainWindow", "New Music File"))
